Move the cleanup into the Dockerfile

diff --git a/images/base/Dockerfile b/images/base/Dockerfile
--- a/images/base/Dockerfile
+++ b/images/base/Dockerfile
@@ -1,10 +1,7 @@
 FROM buildpack-deps:jessie-curl
 MAINTAINER Jesse Rosenberger
 
-WORKDIR /opt/spaceglue
-ONBUILD WORKDIR /opt/spaceglue
 ADD apt-sources.list /etc/apt/sources.list
-COPY scripts .
 
 ARG NODE_VERSION
 ENV NODE_VERSION ${NODE_VERSION:-4.6.1}
@@ -14,9 +11,11 @@ ENV NODESOURCE_BASEURL https://deb.nodesource.com/node_4.x
 ENV NODESOURCE_BASEPATH /pool/main/n/nodejs/
 ENV NODESOURCE_DEB_PATH nodejs_${NODE_VERSION}-1nodesource1~${NODESOURCE_DEBIAN_DIST}1_amd64.deb
 
-ADD "${NODESOURCE_BASEURL}${NODESOURCE_BASEPATH}${NODESOURCE_DEB_PATH}" node.deb
+ADD "${NODESOURCE_BASEURL}${NODESOURCE_BASEPATH}${NODESOURCE_DEB_PATH}" \
+  /tmp/node.deb
 
-RUN (dpkg -i node.deb 2> /dev/null || true) && rm node.deb
+RUN (dpkg -i /tmp/node.deb 2> /dev/null || true) && \
+  rm /tmp/node.deb
 
 RUN apt-get update && apt-get -f install -y && apt-get install -y \
     iptables \
@@ -24,7 +23,16 @@ RUN apt-get update && apt-get -f install -y && apt-get install -y \
 
 RUN ["npm", "install", "--global", "npm@3"]
 
-RUN lib/cleanup.sh
+# Clean up the packages, and our mess.
+RUN npm cache clear && apt-get autoremove -y && rm -rf \
+  /usr/share/doc \
+  /usr/share/doc-base \
+  /usr/share/man \
+  /usr/share/locale \
+  /usr/share/zoneinfo \
+  /var/lib/cache \
+  /var/lib/log \
+  /tmp/*
 
 # For legacy reasons only, we run on port 80
 # This allows Meteor Up to keep doing --port THEIRPORT:80, which is hard-coded
@@ -32,6 +40,16 @@ RUN lib/cleanup.sh
 # thanks to dockers default run cap of NET_BIND_SERVICE=true
 EXPOSE 80
 
+# Create a non-privileged user to do most all the work as.
+# We do this now to create the home directory.
 RUN groupadd -r node && useradd -r -g node node
+
 USER node
+
+# Do the rest in the 'node' user home directory.
+WORKDIR /home/node
+ONBUILD WORKDIR /home/node
+
+COPY scripts .
+
 ENTRYPOINT ./run_app.sh
